# Generated by Django 3.0.2 on 2020-01-19 12:04

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='departure_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='sessionId',
            field=models.CharField(default=datetime.datetime(2020, 1, 19, 12, 4, 27, 702082, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
    ]
